### ISSUE TITLE
The VertexScene::teardown did not check the validity of uniform_buffer_memory before calling vkUnmapMemory

### ISSUE THREAD

**Issue by davidmaoamd** [vkmark/vkmark#12]
I am running the vkmark with newly released [AMDVLK ](https://github.com/GPUOpen-Drivers/AMDVLK)open source vulkan driver, and find an invalid usage of vkUnampMemory.

#0  0x00007ffff2a7b429 in vk::Memory::Unmap (this=0x0) at ../../../../api/vk_memory.cpp:782
#1  0x00007ffff2a7b843 in vk::entry::vkUnmapMemory (device=0x7ffff7eb7010, memory=0x0) at ../../../../api/vk_memory.cpp:899
#2  0x0000000000456890 in vk::Device::unmapMemory (memory=..., this=0x7fffffffe008) at /usr/include/vulkan/vulkan.hpp:23683
#3  VertexScene::teardown (this=0x6f4330) at ../src/scenes/vertex_scene.cpp:107
#4  0x000000000045f3fd in MainLoop::<lambda()>::operator()(void) const (__closure=0x7fffffffdd40) at ../src/main_loop.cpp:115
#5  0x000000000045fb92 in Util::RAIIHelper<void (*)(), MainLoop::run()::<lambda()> >::~RAIIHelper(void) (this=0x7fffffffdd40, __in_chrg=<optimized out>) at ../src/util.h:69
#6  0x000000000045f92d in MainLoop::run (this=0x7fffffffdf20) at ../src/main_loop.cpp:115
#7  0x0000000000406aa8 in main (argc=3, argv=0x7fffffffe228) at ../src/main.cpp:138

Thanks.

**Comment by afrantzis** [comment]
Thanks for the report. In order for "memory" to be zero during scene teardown something must have gone wrong during scene setup. Does the scene run normally before this error is encountered?

I have pushed code to master to make scene teardown more robust in cases of incomplete setup. This will just mitigate the effect not the cause of the issue, but will hopefully allow a clean shutdown so that we can get more information about why you are getting a null memory buffer handle (e.g. if an exception is thrown during setup). Please try with the current master and let me know of any other findings.
